app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::resource('/api/v1/getDataFromPi', 'Api\v1\ApiController@getDataFromPi');

    // Route::get('/api/v1/syncpi', 'ERP\Tms\SyncPiController@index');
    Route::post('/api/v1/syncpi/listen', 'ERP\Tms\SyncPiController@listen');
    Route::get('/api/v1/syncpi/getEmpData', 'ERP\Tms\SyncPiController@getEmpData');
    Route::get('/api/v1/syncpi/getEmpCardData', 'ERP\Tms\SyncPiController@getEmpCardData');
    Route::post('/api/v1/syncpi/syncDoorRecordData', 'ERP\Tms\SyncPiController@syncDoorRecordData');


//    Route::get('/', 'HomeController@index');
    Route::get('/', 'ERP\Tms\ImportDataController@index');
    Route::get('/home', 'HomeController@index');
    Route::get('/home/controller_status', 'HomeController@controllerStatus');

    Route::resource('/emp/employee', 'ERP\Emp\EmployeeController');

    Route::resource('/tms/accesscontroller', 'ERP\Tms\AccessController');
    Route::resource('/tms/workschedule', 'ERP\Tms\WorkScheduleController');
    //Route::post('/tms/sendemail/send', 'ERP\Tms\SendEmailController@send_email');
    Route::resource('/tms/sendemail', 'ERP\Tms\SendEmailController');
    Route::get('/tms/manageemail/delete', 'ERP\Tms\ManageEmailController@destroy');
    Route::resource('/tms/manageemail', 'ERP\Tms\ManageEmailController');

    Route::get('/tms/accesscontroller/{id}/updateEmpData',
        'ERP\Tms\AccessController@updateEmpData');
    Route::get('/tms/accesscontroller/{id}/updateEmpCardData',
        'ERP\Tms\AccessController@updateEmpCardData');

    Route::resource('/auth/user', 'UserController');
    Route::resource('/auth/role', 'RoleController');


    Route::get('/tms/importdata', 'ERP\Tms\ImportDataController@index');
    Route::get('/tms/importdata/process/accdb', 'ERP\Tms\ImportDataController@import_accdb');
    Route::get('/tms/importdata/process/hrms', 'ERP\Tms\ImportDataController@import_dbf');
    Route::get('/tms/importdata/process/ping', 'ERP\Tms\ImportDataController@ping_controller');
    Route::post('/tms/importdata/process/reset', 'ERP\Tms\ImportDataController@reset_sync');

    Route::get('/tms/report/esd', 'ERP\Tms\EsdReportController@index');
    Route::get('/tms/report/esd/export', 'ERP\Tms\EsdReportController@export');
    Route::get('/tms/report/esd/status', 'ERP\Tms\EsdReportController@testStatus');
    Route::get('/tms/report/esd/status/export', 'ERP\Tms\EsdReportController@exportTestStatus');
    Route::get('/tms/report/esd/status/export_mail', 'ERP\Tms\SendEmailController@Export_Mail');
    Route::get('/tms/report/esd/status/exporttomail', 'ERP\Tms\SendEmailController@ExportToMail');

    Route::get('/tms/report/hrms', 'ERP\Tms\HrmsReportController@index');
    Route::get('/tms/report/hrms/exportdat', 'ERP\Tms\HrmsReportController@exportdat');
    Route::get('/tms/report/hrms/exportxls', 'ERP\Tms\HrmsReportController@exportxls');
    Route::get('/tms/report/hrms/rawdata', 'ERP\Tms\HrmsReportController@rawdata');
    Route::get('/tms/report/hrms/rawdata/exportdat', 'ERP\Tms\HrmsReportController@rawdata_exportdat');
    Route::get('/tms/report/hrms/rawdata/exportxls', 'ERP\Tms\HrmsReportController@rawdata_exportxls');

    Route::get('/tms/report/hrms_old', 'ERP\Tms\HrmsReportControllerOld@index');
    Route::get('/tms/report/hrms_old/export', 'ERP\Tms\HrmsReportControllerOld@export');
    Route::get('/tms/report/hrms_old/rawdata', 'ERP\Tms\HrmsReportControllerOld@rawdata');
    Route::get('/tms/report/hrms_old/rawdata/export', 'ERP\Tms\HrmsReportControllerOld@rawdata_export');

    Route::get('/tms/report/graph/{graph}', 'ERP\Tms\GraphReportController@index');
    Route::get('/tms/report/graph/{graph}/ajax', 'ERP\Tms\GraphReportController@ajax');
    Route::get('/tms/report/interplant', 'ERP\Tms\InterplantReportController@index');
    Route::get('/tms/report/interplant/exportxls', 'ERP\Tms\InterplantReportController@exportxls');

});

app/Http/Controllers/ERP/Emp/EmployeeController.php
<?php

namespace App\Http\Controllers\ERP\Emp;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Input, Session, Redirect;

class EmployeeController extends Controller
{

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct(){
    $this->middleware('auth');
  }

  public function index(){
    $tbl_records = array();
    $query = \DB::table('tms_employee AS e')
        ->leftJoin('tms_emp_badge_card AS c', 'e.emp_no' ,'=', 'c.emp_no')
        ->select('e.*','c.card_no');

    if(isset($_GET['emp_no']) && $_GET['emp_no'] !=''){
      $query->where('e.emp_no', '=' ,  $_GET['emp_no']);
    }
    if(isset($_GET['card_no']) && $_GET['card_no'] !=''){
      $query->where('c.card_no', '=' ,  $_GET['card_no']);
    }
    if(isset($_GET['emp_name']) && $_GET['emp_name'] !=''){
      $query->where('e.name', 'like' , '%'.$_GET['emp_name'].'%');
    }
    $employees = $query->paginate(50);
    return view('erp.emp.employee_list', [
          'tbl_records'=>$employees
        ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
      return view('erp.emp.employee_form', []);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      //
      $validator = \Validator::make($request->all(), [
        'name' => 'required|max:255',
        'email' => 'required|email|max:255',
      ]);
      if ($validator->fails()) {
          return redirect('emp/user/create')
                      ->withErrors($validator)
                      ->withInput();
      }else{
        $post = array();
        $post['emp_no'] = $request->input('emp_no');
        $post['name'] = $request->input('name');
        $post['email'] = $request->input('email');
        $post['password'] = bcrypt($request->input('password'));

        $user = \App\TmsEmployee::create($post);
        $user->save();

        foreach($request->input('roles') as $role_id){
          $role = \App\Role::findOrFail($role_id);
          $user->attachRole($role);
        }
        if($user->save()){
            return \Redirect::to('emp/user');
        }

      }

  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
      //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      //
      $post = \App\TmsEmployee::with('department')
        ->with('empgroup')->with('badgecard')->find($id);
      return view('erp.emp.employee_form', ['post'=>$post]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id, Request $request)
  {
      //
      $validator = \Validator::make($request->all(), [
        'name' => 'required|max:255',
        'email' => 'required|email|max:255',
      ]);
      if ($validator->fails()) {
          return redirect('emp/employee/'.$id.'/edit')
                      ->withErrors($validator)
                      ->withInput();
      }else{
        $emp = \App\TmsEmployee::find($id);
        $emp->name = $request->input('name');
        $emp->email = $request->input('email');
        $emp->department_id = $request->input('department_id');
        $emp->group_id = $request->input('group_id');

        if($emp->save()){
          Session::flash('success', $emp->name.' Saved');
          return Redirect::to('emp/employee');
        }

      }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      //
      $user = \App\User::find($id);
      $user->delete();
      return \Redirect::to('emp/user');
  }

}

app/Http/Controllers/ERP/Tms/DashboardReportController.php
<?php

namespace App\Http\Controllers\ERP\Tms;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DashboardReportController extends Controller
{
    //
}

app/Http/Controllers/ERP/Tms/InterplantReportController.php
<?php

namespace App\Http\Controllers\ERP\Tms;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use Carbon\Carbon;

class InterplantReportController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(){
        $this->middleware('auth');
    }


    public function exportxls()
    {
        $results = $this->index(true);
        return view('erp.tms.interplant_export_xls', [
          'tbl_records' => $results->get()
        ]);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($export=false){
        $request = \Request::all(); //<-- we use global request to get the param of URI

        $tbl_records = array();
        if(isset($request['date'])){
            list($start_date, $end_date) = explode(' - ', $request['date']);

            $query = DB::table('tms_interplant_log AS dr')
              ->leftJoin('tms_emp_badge_card AS c', 'dr.card_no', '=', 'c.card_no')
              ->leftJoin('tms_employee AS e', 'c.emp_no', '=', 'e.emp_no')
              ->leftJoin('tms_emp_department AS d', 'e.department_id', '=', 'd.id')
              ->leftJoin('tms_access_controller AS ac', 'ac.id', '=', 'dr.controller_id')
              ->select('dr.*', 'e.name AS emp_name', 'e.emp_no',
                'd.code as department',
                'ac.controller_name')
              ->whereBetween('dr.record_time',[
                Carbon::createFromFormat('d/m/Y H:i', $start_date)->format('Y-m-d H:i:s'),
                Carbon::createFromFormat('d/m/Y H:i', $end_date)->format('Y-m-d H:i:s')
              ]);

            if(isset($request['emp_no']) && $request['emp_no'] != ''){
              $query->where('e.emp_no', $request['emp_no']);
            }
            if(isset($request['card_no']) && $request['card_no'] != ''){
              $query->where('dr.card_no', $request['card_no']);
            }
            if(isset($request['department']) && $request['department'] != ''){
              $query->where('d.code', 'like', $request['department'].'%');
            }
            if(isset($request['pass']) && $request['pass'] != ''){
              $query->where('dr.pass', '=', $request['pass']);
            }
            /*
            if(isset($request['sort'])){
                $query->orderBy($request['sort'], $request['order']);
            }else{*/
                $query->orderBy('dr.card_no', 'ASC');
                $query->orderBy('dr.record_time', 'ASC');
            //}

            if($export == true){
              return $query;
            }
            $tbl_records = $query->paginate(50);
        }
        $sort_link = array(
          'date'=>request('date'),
          'card_no'=>request('card_no'),
          'emp_no'=>request('emp_no'),
          'department'=>request('department'),
        );
        $plant = \App\TmsEmpPlant::pluck('code','id');

        return view('erp.tms.interplant_report', [
          'request' => $request,
          'tbl_records' => $tbl_records,
          'form_url' => url('tms/report/interplant'),
          'export_url' => url('tms/report/interplant/exportxls'),
          'sort_link' => $sort_link,
          'page_title' => 'Interplant Log',
          'plant' => $plant,
        ]);
    }

}

app/Http/Controllers/ERP/Tms/ManageEmailController.php
<?php

namespace App\Http\Controllers\ERP\Tms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use DB;
use App\TmsEmails;
use App\TmsEmployee;
use \Session;

class ManageEmailController extends Controller
{
   /**
    * Create a new controller instance.
    *
    * @return void
    */
   public function __construct()
   {
       $this->middleware('auth');
   }

   /**
    * Show the application dashboard.
    *
    * @return \Illuminate\Http\Response
    */

    /** Laravel resource functions **/

    #GET -> /entity
   public function index(Request $request)
   {
      $view_data = array();
      $id = $request->input('tms_email');
      $view_data['tms_emails'] = TmsEmails::find($id);
      
      $view_data['reporttype'] = array(
        1 => 'ESD test log',
        2 => 'EMP test status'
      );

      $view_data['line'] = DB::table('tms_employee')->select('job')->distinct('job')->where('job', 'like', '%line%')->lists('job', 'job');

      $view_data['department'] = DB::table('tms_emp_department')->select('code')->distinct('code')->leftjoin('tms_employee', 'department_id', '=', 'tms_emp_department.id')->lists('code', 'code');

      $view_data['day'] = array(
        7 => "Sunday",
        1 => "Monday",
        2 => "Tuesday",
        3 => "Wednesday",
        4 => "Thursday",
        5 => "Friday",
        6 => "Saturday"
      );
      
      $users = TmsEmails::paginate('5');
      $view_data['users'] = $users;

      if($request->input('search_email') != null){
        $search_email = $request->input('search_email');
        $view_data['db_search_email'] = TmsEmails::where('emp_emails', 'LIKE', $search_email)->get();
      }else{
        $view_data['db_search_email'] = TmsEmails::where('emp_emails', '=', null)->get();
      }

      return view('erp.tms.manage_email', $view_data);
   }

    #GET -> /entity/create
    public function create()
   {
       return view('events/index');
   }

    #POST -> /entity
    public function store(Request $request)
    {
      $tms_email = new TmsEmails;
      $id = $request->input('id');
      if($id){
        $tms_email = TmsEmails::find($id);
      }

      $email = $request->input('email');
      $result = filter_var( $email, FILTER_VALIDATE_EMAIL );

      if($result == false){
        Session::flash('message_error', "Please enter the correct e-mail address.");
        return redirect('tms/manageemail');
      }else{
        if(isset($email)){
          $tms_email_check = TmsEmails::where('emp_emails', $email)->first();
          if(!$id){
            if($tms_email_check){
              Session::flash('message_error1', "The e-mail existed.");
              return redirect('tms/manageemail');
            }
          }
        }
      }

      $reporttype = $request->input('reporttype');
      $day = $request->input('day');
      $time = $request->input('time');
      $line = $request->input('line');
      $department = $request->input('department');
      $tms_email->emp_emails = $email;
      $tms_email->emp_reports = $reporttype;
      $tms_email->emp_line = $line;
      $tms_email->emp_department = $department;
      $tms_email->emp_days = implode(",", $day);
      $tms_email->emp_times = $time;
      $tms_email->save();
      Session::flash('message_success', "The e-mail has been saved.");
      return redirect('tms/manageemail');
    }

    #GET -> /entity/{vars}
    public function show()
   {
       return view('events/index');
   }

    #GET -> /entity/{single-var}/edit
    public function edit()
   {
       return view('events/index');
   }

    #PUT/PATCH -> /entity/{vars}
    public function update()
   {
       return view('events/index');
   }

    #DELETE -> /entity/{vars}
    public function destroy(Request $request)
    {
      $tms_del_id = $request->input('tms_del_id');
      if($tms_del_id){
        $tms_emails = TmsEmails::find($tms_del_id);
        $tms_emails->delete();
      }
       return redirect('/tms/manageemail');
    }

    /** Laravel resource functions **/

    /** Ajax functions **/

    /** Ajax functions **/

    /** Controller functions **/

    /** Controller functions **/

    /** Static functions **/
    /** Static functions **/

}


/*

{


   public function manage_email(Request $request){
  dd($request->all());
                        foreach ($em_query as $em) {
                            $insert_temp_emails[] = [
                                'emails' => $em->emails,
                                'reporttype' => $em->reporttype,
                                'frequency' => $em->frequency
                            ];

                        }

                $start_date->addDay();
                foreach(array_chunk($insert_temp_query, 1000) as $t){
                    DB::table('temp_tms_door_record_raw')->insert($t);
                }
                $insert_temp_query = array();

  }
}

*/

resources/views/theme/default/erp/tms/accesscontroller_form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">Access Controller</div>
        <div class="panel-body">
        @if(isset($post['id']))
            {!! Form::model($post, ['url' => array('tms/accesscontroller', $post['id']), 'method' => 'PUT']) !!}
        @else
            {!! Form::open(['url' => 'tms/accesscontroller']) !!}
        @endif
                <div class="row">
                    <div class="col-md-12 form-group">
                        <label class="col-md-2 control-label">Controller No</label>
                        <div class="col-md-10">
                            {{ Form::text(
                                'controller[controller_no]',
                                null, ['class'=>'form-control'])
                            }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="col-md-2 control-label">Controller Name</label>
                        <div class="col-md-10">

                            {{ Form::text(
                                'controller[controller_name]',
                                null, ['class'=>'form-control'])
                            }}

                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="col-md-2 control-label">Controller IP</label>
                        <div class="col-md-10">

                            {{ Form::text(
                                'controller[controller_ip]',
                                null, ['class'=>'form-control'])
                            }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="col-md-2 control-label">Attendance Group</label>
                        <div class="col-md-10">
                            @foreach($attendancegroup as $attngroup)
                                <label>
                                    {{ Form::checkbox('attn['.$attngroup->id.']', $attngroup->id) }}
                                    {{ $attngroup->code }}
                                </label>
                            @endforeach
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input type="submit" class="btn btn-primary" name="submit" value="Save">
                            @if(isset($post['id']))
                                <a class="btn btn-danger pull-right"  onclick="document.getElementById('deleteform').submit();return false;">Delete</a>
                            @endif
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
            @if(isset($post['id']))
                <form id="deleteform" style="display:none;" action="{{ route('tms.accesscontroller.destroy', $post['id']) }}" method="POST">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="submit" value="Delete">
                </form>
            @endif
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_js')
<script>
  $('.datepicker').daterangepicker({
        showDropdowns: true,
        timePicker: true,
        locale: {
          // format: 'DD/MM/YYYY H:mm'
          format: 'DD/MM/YYYY H:mm'
        },
    },
    function(start, end, label) {
        // var years = moment().diff(start, 'years');
        // console.log("You are " + years + " years old.");
    });
</script>
@endsection

resources/views/theme/default/erp/tms/esd_report.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">{{ $page_title }}</div>
        <div class="panel-body">
          <form class="form-horizontal" role="form" method="GET" action="{{ $form_url }}">
            {!! csrf_field() !!}
            <div class="form-group">
                <div class="col-md-3  {{ $errors->has('date') ? ' has-error' : '' }}">
                    <input type="text" class="form-control datepicker" placeholder="Date.." name="date" value="{{ request('date')!=''?request('date'):date('d/m/Y H:i') }}">
                </div>
                <div class="col-md-7 row">
                    <div class="col-md-2 row">
                       <input type="text" class="form-control" placeholder="Card No.." name="card_no" value="{{ request('card_no') }}">
                    </div>
                    <div class="col-md-2 ">
                       <input type="text" class="form-control" placeholder="Emp No.." name="emp_no" value="{{ request('emp_no') }}">
                    </div>
                    <div class="col-md-8 row">
                        <div class="col-md-4 row">
                          {{ Form::select(
                              'job',
                              [''=>'Line']+$job->all(),
                              request('job'),
                              ['class'=>'form-control'])
                          }}
                            <!--<input type="text" class="form-control" placeholder="Line" name="job" value="{{ request('job') }}">-->
                        </div>

                        <div class="col-md-3" style="width: 150px;">
                        {{ Form::select(
                            'department',
                            [''=>'Department']+$department->all(),
                            request('department'),
                            ['class'=>'form-control'])
                        }}
                        </div>

                       <div class="col-md-3 row">
                        {{ Form::select(
                            'test_result',
                            [''=>'All', '-1'=>'Not Tested', '0'=>'Fail', '1'=>'Pass'],
                            request('test_result'),
                            ['class'=>'form-control'])
                        }}
                        </div>
                        <!--<div class="col-md-1 checkbox">
                            <label ><input type="checkbox" name="out" value="1" {{ (request('out'))?'checked="checked"':''  }}> Out</label>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-2 text-right pull-right">
                    <div class="">
                      <button type="submit" class="btn btn-primary">
                        <i class="fa fa-btn fa-search"></i>
                      </button>
                      <?php if(isset($_GET['date'])){ ?>
                        <a class="btn btn-default" onclick="window.location='{{ $export_url }}?'+window.location.href.split('?')[1]">
                          <i class="fa fa-btn fa-download"></i>
                        </a>
                      <?php } ?>
                    </div>
                </div>
            </form>
          </div>
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-condensed">
              <thead>
                <tr>
                  <th>@sortablelink('dr.record_time', 'Record Date & Time')</a></th>
                  <th>@sortablelink('dr.card_no', 'Card No')</th>
                  <th>@sortablelink('e.emp_no', 'Employee No')</th>
                  <th>@sortablelink('e.name', 'Employee Name')</th>
                  <th>@sortablelink('e.job', 'Line')</th>
                    <!-- Reverse left foot and wriststrap col due to Access Control Software -->
                  <th>@sortablelink('lh.hvalue_en', 'Wrist Strap')</th>
                  <th>@sortablelink('h.hvalue_en', 'Left Foot')</th>
                  <th>@sortablelink('rh.hvalue_en', 'Right Foot')</th>
                  <th>@sortablelink('dr.pass_flag', 'Result')</th>
                  <!--<th>@sortablelink('p.power_name', 'Test Method')</th>-->
                  <th>@sortablelink('ac.controller_name', 'Controller')</th>
                  <!--<th>@sortablelink('dr.record_state', 'Direction')</th>-->
                  <th>@sortablelink('dr.record_state', 'Status')</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($tbl_records as $record)
                  <?php
                  if($record->pass_flag == '1'){
                    $record->pass_flag_name = 'Pass';
                    $record->pass_flag_class = 'pass';
                  } elseif($record->pass_flag == '0') {
                    if($record->open_type == '255'){
                        $record->pass_flag_name = 'Invalid Card';
                        $record->pass_flag_class = 'fail';
                    }else if($record->open_type == '2'){
                        $record->pass_flag_name = 'Fail';
                        $record->pass_flag_class = 'fail';
                    }else{
                        $record->pass_flag_name = 'Fail';
                        $record->pass_flag_class = 'fail';
                    }
                  } else{
                    $record->pass_flag_name = 'Not tested';
                    $record->pass_flag_class = 'not-tested';
                  }
                  if($record->record_state==1){
                    $direction = 'IN';
                  }else if($record->record_state==2){
                    $direction = 'OUT';
                  }else{
                    $direction = '';
                  }
                  ?>
                  <tr class="{{ $record->pass_flag_class }}">
                    <td>{{ $record->record_time }}</td>
                    <td>{{ $record->card_no }}</td>
                    <td>{{ $record->emp_no }}</td>
                    <td>{{ $record->emp_name }}</td>
                    <td>{{ $record->job }}</td>
                    <!-- Reverse left foot and wriststrap col due to Access Control Software -->
                    <td>{{ $record->lhvalue_en }}</td>
                    <td>{{ $record->hvalue_en }}</td>
                    <td>{{ $record->rhvalue_en }}</td>
                    <td>{{ $record->pass_flag_name }}</td>
                    <!--<td>{{ $record->power_name }}</td>-->
                    <td>{{ $record->controller_name }}</td>
                    <td>{{ $direction }} </td>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
            @if (COUNT($tbl_records)>0)
              {!!
                  $tbl_records->appends(Request::except('page'))->render()
              !!}
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_js')
<script>
  $('.datepicker').daterangepicker({
    @if(url('tms/report/esd/status') == $form_url)
        singleDatePicker: true,
    @endif
        showDropdowns: true,
        timePicker: true,
        locale: {
          // format: 'DD/MM/YYYY H:mm'
          format: 'DD/MM/YYYY H:mm'
        },
    });
</script>
@endsection